### ISSUE TITLE
Stable release ?

### ISSUE THREAD

**Issue by Okipa** [vkovic/laravel-model-meta#2]
Hi @vkovic,

Would you consider to release your package in a stable version soon ?  
This could engage community to use it in production and to target and fix the last undiscovered bugs.  
I am interested to use your package in production but not in unstable release tag because it means breaking changes could occur.  
I use it for a few days now and everything seems to be OK so far.

Let me know and thanks for the good work !

**Comment by vkovic** [comment]
Hi @Okipa, 

Yes, actually my idea was to let it be used for a while and see a community reactions.
The problem is the lack of time, so I did not get opportunity to promote it.

On the other side I'm using it in a couple of projects and everything is working as expected, so
I think I can review code one more time and promote it to version `1.0.0` in couple of days.

**Comment by Okipa** [comment]
Nice, thanks !
You can count on me to send you a PR if I encounter a problem anyway.

**Comment by vkovic** [comment]
Great!

Watch for the version change 😄
